apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-depl
  namespace: prd
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD        # Set the MySQL root password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql        # MySQL data directory
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim        # Link to PVC created earlier

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: prd
spec:
  ports:
    - port: 3306
  selector:
    app: mysql