apiVersion: v1
kind: ConfigMap
metadata:
  name: taskmanagement-configs-uat
  namespace: uat
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service-uat:3306/taskmanagement"