apiVersion: v1
kind: Secret
metadata:
  name: taskmanagement-secrets
  namespace: prd
type: Opaque
data:
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: cm9vdA==
  TASK_TRACKER_JWT_SECRET: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXpBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OTBhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ekFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5MA==