spring:
  datasource:
    url: jdbc:sqlite:/Users/onggowahyudi/nus/task-tracker-api/resources/db/tasktracker.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: task-processing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      topics :


    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer




task-tracker:
  jwt:
    secret: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
    expirationTimeInMins: 10

logging:
  config: classpath:log4j2-dev.xml


